<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DashboardServer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Aloe.Apps.DashboardLib/Aloe.Apps.DashboardLib.csproj" />
    <ProjectReference Include="../../../Libs/Aloe.Libs.PicoBlazor/Aloe.Libs.PicoBlazor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
