<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Aloe.Medock.Reservation.$(MSBuildProjectName)</RootNamespace>
    <StartupObject></StartupObject>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <UserSecretsId>6d08ce26-9950-4a19-9f4c-94746eb476d6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="bookmark_schedule_date_appointment_icon_124679.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\bookmark_schedule_date_appointment_icon_124679.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.2.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="NetTopologySuite" Version="2.5.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
    <PackageReference Include="ReactiveProperty.WPF" Version="9.6.0" />
    <PackageReference Include="Serilog.Sinks.RichTextBox.Wpf" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Aloe.Common.AloeCoreLib.Wpf\Aloe.Common.AloeCoreLib.Wpf.csproj" />
    <ProjectReference Include="..\..\..\Common\AloeCoreLib.Client\Aloe.Common.AloeCoreLib.Client.csproj" />
    <ProjectReference Include="..\..\..\Common\AloeCoreLib\Aloe.Common.AloeCoreLib.csproj" />
    <ProjectReference Include="..\AloeMedockResvLib.Logging\Aloe.Medock.Reservation.AloeMedockResvLib.Logging.csproj" />
    <ProjectReference Include="..\AloeMedockResvLib\Aloe.Medock.Reservation.AloeMedockResvLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Cust\OrganizationBar.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Cust\OrganizationBasicPanel.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Cust\PatientInsuranceCardTabItem.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\Cust\OrganizationWindow.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
</Project>
