-- Project Name : aloe_reservation_grid
-- Date/Time    : 2024/12/24 15:10:04
-- Author       : user
-- RDBMS Type   : PostgreSQL
-- Application  : A5:SQL Mk-2

/*
  << 注意！！ >>
  BackupToTempTable, RestoreFromTempTable疑似命令が付加されています。
  これにより、drop table, create table 後もデータが残ります。
  この機能は一時的に $$TableName のような一時テーブルを作成します。
  この機能は A5:SQL Mk-2でのみ有効であることに注意してください。
*/

-- organization_patients
-- * BackupToTempTable
DROP TABLE if exists organization_patients CASCADE;

-- * RestoreFromTempTable
CREATE TABLE organization_patients (
  org_pt_id integer NOT NULL
  , org_id integer DEFAULT 0 NOT NULL
  , pt_id integer DEFAULT 0 NOT NULL
  , personal_number TEXT DEFAULT '' NOT NULL
  , department TEXT DEFAULT '' NOT NULL
  , is_member BOOLEAN DEFAULT FALSE NOT NULL
  , start_date date
  , end_date date
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

CREATE UNIQUE INDEX organization_patients_PKI
  ON organization_patients(org_pt_id);

ALTER TABLE organization_patients
  ADD CONSTRAINT organization_patients_PKC PRIMARY KEY (org_pt_id);

-- patient_remark_codes
-- * BackupToTempTable
DROP TABLE if exists patient_remark_codes CASCADE;

-- * RestoreFromTempTable
CREATE TABLE patient_remark_codes (
  pt_remark_code integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , pt_remark_name TEXT DEFAULT '' NOT NULL
  , pt_remark_mark TEXT DEFAULT '' NOT NULL
  , seq integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- organization_remark_codes
-- * BackupToTempTable
DROP TABLE if exists organization_remark_codes CASCADE;

-- * RestoreFromTempTable
CREATE TABLE organization_remark_codes (
  org_remark_code integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , org_remark_name TEXT DEFAULT '' NOT NULL
  , org_remark_mark TEXT DEFAULT '' NOT NULL
  , seq integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- patient_insurance_cards
-- * BackupToTempTable
DROP TABLE if exists patient_insurance_cards CASCADE;

-- * RestoreFromTempTable
CREATE TABLE patient_insurance_cards (
  pt_insur_card_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , pt_id integer DEFAULT 0 NOT NULL
  , is_primary BOOLEAN DEFAULT FALSE NOT NULL
  , insur_prov_type_code integer DEFAULT 0 NOT NULL
  , insur_prov_id integer DEFAULT 0 NOT NULL
  , insur_prov_number TEXT DEFAULT '' NOT NULL
  , insur_prov_name TEXT DEFAULT '' NOT NULL
  , insured_code TEXT DEFAULT '' NOT NULL
  , insured_code_symbol TEXT DEFAULT '' NOT NULL
  , insured_code_number TEXT DEFAULT '' NOT NULL
  , insured_code_branch_number TEXT DEFAULT '' NOT NULL
  , insured_person_name TEXT DEFAULT '' NOT NULL
  , self_family_relationship_code TEXT DEFAULT '' NOT NULL
  , assistance_code TEXT DEFAULT '' NOT NULL
  , continuation_code TEXT DEFAULT '' NOT NULL
  , start_date date
  , end_date date
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- patient_remarks
-- * BackupToTempTable
DROP TABLE if exists patient_remarks CASCADE;

-- * RestoreFromTempTable
CREATE TABLE patient_remarks (
  pt_remark_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , pt_id integer DEFAULT 0 NOT NULL
  , pt_remark_code integer DEFAULT 0 NOT NULL
  , pt_remark_text TEXT DEFAULT '' NOT NULL
  , updated_user_name TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- patient_contacts
-- * BackupToTempTable
DROP TABLE if exists patient_contacts CASCADE;

-- * RestoreFromTempTable
CREATE TABLE patient_contacts (
  pt_ctc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , pt_id integer DEFAULT 0 NOT NULL
  , ctc_name TEXT DEFAULT '' NOT NULL
  , is_primary BOOLEAN DEFAULT FALSE NOT NULL
  , is_form_shipping BOOLEAN DEFAULT FALSE NOT NULL
  , is_result_shipping BOOLEAN DEFAULT FALSE NOT NULL
  , is_billing BOOLEAN DEFAULT FALSE NOT NULL
  , zip_code TEXT DEFAULT '' NOT NULL
  , ard1 TEXT DEFAULT '' NOT NULL
  , ard2 TEXT DEFAULT '' NOT NULL
  , ard3 TEXT DEFAULT '' NOT NULL
  , recipient_name TEXT DEFAULT '' NOT NULL
  , honorific TEXT DEFAULT '' NOT NULL
  , tel TEXT DEFAULT '' NOT NULL
  , tel2 TEXT DEFAULT '' NOT NULL
  , fax TEXT DEFAULT '' NOT NULL
  , email TEXT DEFAULT '' NOT NULL
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- organization_remarks
-- * BackupToTempTable
DROP TABLE if exists organization_remarks CASCADE;

-- * RestoreFromTempTable
CREATE TABLE organization_remarks (
  org_remark_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , org_id integer DEFAULT 0 NOT NULL
  , org_remark_code integer DEFAULT 0 NOT NULL
  , org_remark_text TEXT DEFAULT '' NOT NULL
  , updated_user_name TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- organization_contacts
-- * BackupToTempTable
DROP TABLE if exists organization_contacts CASCADE;

-- * RestoreFromTempTable
CREATE TABLE organization_contacts (
  org_ctc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , org_id integer DEFAULT 0 NOT NULL
  , ctc_name TEXT DEFAULT '' NOT NULL
  , is_primary BOOLEAN DEFAULT FALSE NOT NULL
  , is_form_shipping BOOLEAN DEFAULT FALSE NOT NULL
  , is_result_shipping BOOLEAN DEFAULT FALSE NOT NULL
  , is_billing BOOLEAN DEFAULT FALSE NOT NULL
  , zip_code TEXT DEFAULT '' NOT NULL
  , ard1 TEXT DEFAULT '' NOT NULL
  , ard2 TEXT DEFAULT '' NOT NULL
  , ard3 TEXT DEFAULT '' NOT NULL
  , recipient_name TEXT DEFAULT '' NOT NULL
  , honorific TEXT DEFAULT '' NOT NULL
  , tel TEXT DEFAULT '' NOT NULL
  , tel2 TEXT DEFAULT '' NOT NULL
  , fax TEXT DEFAULT '' NOT NULL
  , email TEXT DEFAULT '' NOT NULL
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- insurance_providers
-- * BackupToTempTable
DROP TABLE if exists insurance_providers CASCADE;

-- * RestoreFromTempTable
CREATE TABLE insurance_providers (
  insur_prov_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , insur_prov_type_code integer DEFAULT 0 NOT NULL
  , insur_prov_number TEXT DEFAULT '' NOT NULL
  , insur_prov_name TEXT DEFAULT '' NOT NULL
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- policies
-- * BackupToTempTable
DROP TABLE if exists policies CASCADE;

-- * RestoreFromTempTable
CREATE TABLE policies (
  policy_code TEXT DEFAULT '' NOT NULL
  , policy_name TEXT DEFAULT '' NOT NULL
  , data_type TEXT DEFAULT '' NOT NULL
  , policy_value TEXT DEFAULT '' NOT NULL
  , policy_desc TEXT DEFAULT '' NOT NULL
  , is_active BOOLEAN DEFAULT FALSE NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

CREATE UNIQUE INDEX policies_PKI
  ON policies(policy_code);

ALTER TABLE policies
  ADD CONSTRAINT policies_PKC PRIMARY KEY (policy_code);

-- user_roles
-- * BackupToTempTable
DROP TABLE if exists user_roles CASCADE;

-- * RestoreFromTempTable
CREATE TABLE user_roles (
  user_id integer NOT NULL
  , role_id integer NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

CREATE UNIQUE INDEX user_roles_PKI
  ON user_roles(user_id,role_id);

ALTER TABLE user_roles
  ADD CONSTRAINT user_roles_PKC PRIMARY KEY (user_id,role_id);

-- roles
-- * BackupToTempTable
DROP TABLE if exists roles CASCADE;

-- * RestoreFromTempTable
CREATE TABLE roles (
  role_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , role_name TEXT DEFAULT '' NOT NULL
  , role_desc TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- role_permissions
-- * BackupToTempTable
DROP TABLE if exists role_permissions CASCADE;

-- * RestoreFromTempTable
CREATE TABLE role_permissions (
  role_id integer NOT NULL
  , perm_id integer NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

CREATE UNIQUE INDEX role_permissions_PKI
  ON role_permissions(role_id,perm_id);

ALTER TABLE role_permissions
  ADD CONSTRAINT role_permissions_PKC PRIMARY KEY (role_id,perm_id);

-- permissions
-- * BackupToTempTable
DROP TABLE if exists permissions CASCADE;

-- * RestoreFromTempTable
CREATE TABLE permissions (
  perm_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , perm_name TEXT DEFAULT '' NOT NULL
  , perm_desc TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- users
-- * BackupToTempTable
DROP TABLE if exists users CASCADE;

-- * RestoreFromTempTable
CREATE TABLE users (
  user_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , login_name TEXT DEFAULT '' NOT NULL
  , email TEXT DEFAULT '' NOT NULL
  , display_name TEXT DEFAULT '' NOT NULL
  , password_hash TEXT DEFAULT '' NOT NULL
  , password_salt TEXT DEFAULT '' NOT NULL
  , expire_date date DEFAULT '9999-12-31' NOT NULL
  , failed_attempt_count integer DEFAULT 0 NOT NULL
  , locked_until_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , last_login_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , last_logout_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , user_info JSONB DEFAULT '{}' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- patients
-- * BackupToTempTable
DROP TABLE if exists patients CASCADE;

-- * RestoreFromTempTable
CREATE TABLE patients (
  pt_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , karte_number TEXT DEFAULT '' NOT NULL
  , pt_full_name TEXT DEFAULT '' NOT NULL
  , pt_full_name_katakana TEXT DEFAULT '' NOT NULL
  , pt_full_name_katakana_normalized TEXT DEFAULT '' NOT NULL
  , pt_given_name TEXT DEFAULT '' NOT NULL
  , pt_old_full_name TEXT DEFAULT '' NOT NULL
  , birth_date date DEFAULT CURRENT_DATE NOT NULL
  , sex_code integer DEFAULT 0 NOT NULL
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- organizations
-- * BackupToTempTable
DROP TABLE if exists organizations CASCADE;

-- * RestoreFromTempTable
CREATE TABLE organizations (
  org_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , insur_prov_type_code integer DEFAULT 0 NOT NULL
  , insur_prov_id integer DEFAULT 0 NOT NULL
  , parent_org_id integer DEFAULT 0 NOT NULL
  , org_number TEXT DEFAULT '' NOT NULL
  , org_name TEXT DEFAULT '' NOT NULL
  , org_name_katakana TEXT DEFAULT '' NOT NULL
  , org_name_katakana_normalized TEXT DEFAULT '' NOT NULL
  , org_name_display TEXT DEFAULT '' NOT NULL
  , org_name_print TEXT DEFAULT '' NOT NULL
  , memo TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_daily_bookings
-- * BackupToTempTable
DROP TABLE if exists reservation_daily_bookings CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_daily_bookings (
  resv_daily_bkg_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , bkg_date date
  , floor_id integer DEFAULT 0 NOT NULL
  , slot TEXT DEFAULT '' NOT NULL
  , ampm_code integer DEFAULT 0 NOT NULL
  , sex_code integer DEFAULT 0 NOT NULL
  , bkg_user_id integer DEFAULT 0 NOT NULL
  , bkg_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , bkg_symbol_text TEXT DEFAULT '' NOT NULL
  , bkg_remark_text TEXT DEFAULT '' NOT NULL
  , is_held BOOLEAN DEFAULT FALSE NOT NULL
  , org_id integer DEFAULT 0 NOT NULL
  , resv_count integer DEFAULT 0 NOT NULL
  , pt_id integer DEFAULT 0 NOT NULL
  , order_id integer DEFAULT 0 NOT NULL
  , sub_order_id integer DEFAULT 0 NOT NULL
  , is_cancelled BOOLEAN DEFAULT FALSE NOT NULL
  , noshow_count integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_daily_slots
-- * BackupToTempTable
DROP TABLE if exists reservation_daily_slots CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_daily_slots (
  resv_daily_slot_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , start_date date DEFAULT CURRENT_DATE NOT NULL
  , end_date date DEFAULT CURRENT_DATE NOT NULL
  , dow_code integer DEFAULT 0 NOT NULL
  , floor_id integer DEFAULT 0 NOT NULL
  , room_id integer DEFAULT 0 NOT NULL
  , daily_cap integer DEFAULT 0 NOT NULL
  , am_cap integer DEFAULT 0 NOT NULL
  , pm_cap integer DEFAULT 0 NOT NULL
  , slots TEXT DEFAULT '' NOT NULL
  , slot_caps TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_rooms
-- * BackupToTempTable
DROP TABLE if exists reservation_rooms CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_rooms (
  room_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , room_name TEXT DEFAULT '' NOT NULL
  , room_desc TEXT DEFAULT '' NOT NULL
  , floor_id integer DEFAULT 0 NOT NULL
  , exam_cat_id integer DEFAULT 0 NOT NULL
  , seq integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_equipment_bookings
-- * BackupToTempTable
DROP TABLE if exists reservation_equipment_bookings CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_equipment_bookings (
  resv_equip_bkg_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , bkg_date date
  , equip_id integer DEFAULT 0 NOT NULL
  , slot TEXT DEFAULT '' NOT NULL
  , bkg_user_id integer DEFAULT 0 NOT NULL
  , bkg_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , bkg_symbol_text TEXT DEFAULT '' NOT NULL
  , bkg_remark_text TEXT DEFAULT '' NOT NULL
  , is_held BOOLEAN DEFAULT FALSE NOT NULL
  , org_id integer DEFAULT 0 NOT NULL
  , pt_id integer DEFAULT 0 NOT NULL
  , order_id integer DEFAULT 0 NOT NULL
  , sub_order_id integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_equipments
-- * BackupToTempTable
DROP TABLE if exists reservation_equipments CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_equipments (
  equip_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , equip_name TEXT DEFAULT '' NOT NULL
  , equip_desc TEXT DEFAULT '' NOT NULL
  , seq integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_floors
-- * BackupToTempTable
DROP TABLE if exists reservation_floors CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_floors (
  floor_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , floor_name TEXT DEFAULT '' NOT NULL
  , floor_desc TEXT DEFAULT '' NOT NULL
  , seq integer DEFAULT 0 NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

-- reservation_equipment_slots
-- * BackupToTempTable
DROP TABLE if exists reservation_equipment_slots CASCADE;

-- * RestoreFromTempTable
CREATE TABLE reservation_equipment_slots (
  resv_equip_slot_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , start_date date DEFAULT CURRENT_DATE NOT NULL
  , end_date date DEFAULT CURRENT_DATE NOT NULL
  , dow_code integer DEFAULT -1 NOT NULL
  , equip_id integer DEFAULT 0 NOT NULL
  , slots TEXT DEFAULT '' NOT NULL
  , is_deleted BOOLEAN DEFAULT FALSE NOT NULL
  , created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , created_user_id integer DEFAULT 0 NOT NULL
  , created_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
  , updated_user_id integer DEFAULT 0 NOT NULL
  , updated_session_id UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
) ;

COMMENT ON TABLE organization_patients IS 'organization_patients';
COMMENT ON COLUMN organization_patients.org_pt_id IS 'org_pt_id';
COMMENT ON COLUMN organization_patients.org_id IS 'org_id:複数回同じ会社もありえる';
COMMENT ON COLUMN organization_patients.pt_id IS 'pt_id';
COMMENT ON COLUMN organization_patients.personal_number IS 'personal_number:社員番号、学生番号';
COMMENT ON COLUMN organization_patients.department IS 'department';
COMMENT ON COLUMN organization_patients.is_member IS 'is_member';
COMMENT ON COLUMN organization_patients.start_date IS 'start_date';
COMMENT ON COLUMN organization_patients.end_date IS 'end_date';
COMMENT ON COLUMN organization_patients.memo IS 'memo';
COMMENT ON COLUMN organization_patients.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN organization_patients.created_at IS 'created_at';
COMMENT ON COLUMN organization_patients.created_user_id IS 'created_user_id';
COMMENT ON COLUMN organization_patients.created_session_id IS 'created_session_id';
COMMENT ON COLUMN organization_patients.updated_at IS 'updated_at';
COMMENT ON COLUMN organization_patients.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN organization_patients.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE patient_remark_codes IS 'patient_remark_codes';
COMMENT ON COLUMN patient_remark_codes.pt_remark_code IS 'pt_remark_code';
COMMENT ON COLUMN patient_remark_codes.pt_remark_name IS 'pt_remark_name';
COMMENT ON COLUMN patient_remark_codes.pt_remark_mark IS 'pt_remark_mark';
COMMENT ON COLUMN patient_remark_codes.seq IS 'seq';
COMMENT ON COLUMN patient_remark_codes.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN patient_remark_codes.created_at IS 'created_at';
COMMENT ON COLUMN patient_remark_codes.created_user_id IS 'created_user_id';
COMMENT ON COLUMN patient_remark_codes.created_session_id IS 'created_session_id';
COMMENT ON COLUMN patient_remark_codes.updated_at IS 'updated_at';
COMMENT ON COLUMN patient_remark_codes.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN patient_remark_codes.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE organization_remark_codes IS 'organization_remark_codes';
COMMENT ON COLUMN organization_remark_codes.org_remark_code IS 'org_remark_code';
COMMENT ON COLUMN organization_remark_codes.org_remark_name IS 'org_remark_name';
COMMENT ON COLUMN organization_remark_codes.org_remark_mark IS 'org_remark_mark';
COMMENT ON COLUMN organization_remark_codes.seq IS 'seq';
COMMENT ON COLUMN organization_remark_codes.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN organization_remark_codes.created_at IS 'created_at';
COMMENT ON COLUMN organization_remark_codes.created_user_id IS 'created_user_id';
COMMENT ON COLUMN organization_remark_codes.created_session_id IS 'created_session_id';
COMMENT ON COLUMN organization_remark_codes.updated_at IS 'updated_at';
COMMENT ON COLUMN organization_remark_codes.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN organization_remark_codes.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE patient_insurance_cards IS 'patient_insurance_cards';
COMMENT ON COLUMN patient_insurance_cards.pt_insur_card_id IS 'pt_insur_card_id';
COMMENT ON COLUMN patient_insurance_cards.pt_id IS 'pt_id';
COMMENT ON COLUMN patient_insurance_cards.is_primary IS 'is_primary:主保険';
COMMENT ON COLUMN patient_insurance_cards.insur_prov_type_code IS 'insur_prov_type_code:0=None, 1=協会けんぽ, 2=代行機関, 3=健康保険組合, 4=国保, 5=その他';
COMMENT ON COLUMN patient_insurance_cards.insur_prov_id IS 'insur_prov_id';
COMMENT ON COLUMN patient_insurance_cards.insur_prov_number IS 'insur_prov_number';
COMMENT ON COLUMN patient_insurance_cards.insur_prov_name IS 'insur_prov_name:保険者名';
COMMENT ON COLUMN patient_insurance_cards.insured_code IS 'insured_code:記号、番号、枝番';
COMMENT ON COLUMN patient_insurance_cards.insured_code_symbol IS 'insured_code_symbol:記号';
COMMENT ON COLUMN patient_insurance_cards.insured_code_number IS 'insured_code_number:番号';
COMMENT ON COLUMN patient_insurance_cards.insured_code_branch_number IS 'insured_code_branch_number:枝番';
COMMENT ON COLUMN patient_insurance_cards.insured_person_name IS 'insured_person_name:被保険者名';
COMMENT ON COLUMN patient_insurance_cards.self_family_relationship_code IS 'self_family_relationship_code:本人家族区分(1=Self[本人], 2=Dependents[家族])';
COMMENT ON COLUMN patient_insurance_cards.assistance_code IS 'assistance_code:補助区分(0=国保0割,A船員1割)';
COMMENT ON COLUMN patient_insurance_cards.continuation_code IS 'continuation_code:任意継続(0=None, 1=ExtendedCare[継続療養], 2=VoluntaryContinuation[任意継続])';
COMMENT ON COLUMN patient_insurance_cards.start_date IS 'start_date';
COMMENT ON COLUMN patient_insurance_cards.end_date IS 'end_date';
COMMENT ON COLUMN patient_insurance_cards.memo IS 'memo';
COMMENT ON COLUMN patient_insurance_cards.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN patient_insurance_cards.created_at IS 'created_at';
COMMENT ON COLUMN patient_insurance_cards.created_user_id IS 'created_user_id';
COMMENT ON COLUMN patient_insurance_cards.created_session_id IS 'created_session_id';
COMMENT ON COLUMN patient_insurance_cards.updated_at IS 'updated_at';
COMMENT ON COLUMN patient_insurance_cards.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN patient_insurance_cards.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE patient_remarks IS 'patient_remarks';
COMMENT ON COLUMN patient_remarks.pt_remark_id IS 'pt_remark_id';
COMMENT ON COLUMN patient_remarks.pt_id IS 'pt_id';
COMMENT ON COLUMN patient_remarks.pt_remark_code IS 'pt_remark_code';
COMMENT ON COLUMN patient_remarks.pt_remark_text IS 'pt_remark_text';
COMMENT ON COLUMN patient_remarks.updated_user_name IS 'updated_user_name';
COMMENT ON COLUMN patient_remarks.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN patient_remarks.created_at IS 'created_at';
COMMENT ON COLUMN patient_remarks.created_user_id IS 'created_user_id';
COMMENT ON COLUMN patient_remarks.created_session_id IS 'created_session_id';
COMMENT ON COLUMN patient_remarks.updated_at IS 'updated_at';
COMMENT ON COLUMN patient_remarks.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN patient_remarks.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE patient_contacts IS 'patient_contacts';
COMMENT ON COLUMN patient_contacts.pt_ctc_id IS 'pt_ctc_id';
COMMENT ON COLUMN patient_contacts.pt_id IS 'pt_id';
COMMENT ON COLUMN patient_contacts.ctc_name IS 'ctc_name';
COMMENT ON COLUMN patient_contacts.is_primary IS 'is_primary';
COMMENT ON COLUMN patient_contacts.is_form_shipping IS 'is_form_shipping';
COMMENT ON COLUMN patient_contacts.is_result_shipping IS 'is_result_shipping';
COMMENT ON COLUMN patient_contacts.is_billing IS 'is_billing';
COMMENT ON COLUMN patient_contacts.zip_code IS 'zip_code';
COMMENT ON COLUMN patient_contacts.ard1 IS 'ard1';
COMMENT ON COLUMN patient_contacts.ard2 IS 'ard2';
COMMENT ON COLUMN patient_contacts.ard3 IS 'ard3';
COMMENT ON COLUMN patient_contacts.recipient_name IS 'recipient_name';
COMMENT ON COLUMN patient_contacts.honorific IS 'honorific';
COMMENT ON COLUMN patient_contacts.tel IS 'tel';
COMMENT ON COLUMN patient_contacts.tel2 IS 'tel2';
COMMENT ON COLUMN patient_contacts.fax IS 'fax';
COMMENT ON COLUMN patient_contacts.email IS 'email';
COMMENT ON COLUMN patient_contacts.memo IS 'memo';
COMMENT ON COLUMN patient_contacts.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN patient_contacts.created_at IS 'created_at';
COMMENT ON COLUMN patient_contacts.created_user_id IS 'created_user_id';
COMMENT ON COLUMN patient_contacts.created_session_id IS 'created_session_id';
COMMENT ON COLUMN patient_contacts.updated_at IS 'updated_at';
COMMENT ON COLUMN patient_contacts.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN patient_contacts.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE organization_remarks IS 'organization_remarks';
COMMENT ON COLUMN organization_remarks.org_remark_id IS 'org_remark_id';
COMMENT ON COLUMN organization_remarks.org_id IS 'org_id';
COMMENT ON COLUMN organization_remarks.org_remark_code IS 'org_remark_code';
COMMENT ON COLUMN organization_remarks.org_remark_text IS 'org_remark_text';
COMMENT ON COLUMN organization_remarks.updated_user_name IS 'updated_user_name';
COMMENT ON COLUMN organization_remarks.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN organization_remarks.created_at IS 'created_at';
COMMENT ON COLUMN organization_remarks.created_user_id IS 'created_user_id';
COMMENT ON COLUMN organization_remarks.created_session_id IS 'created_session_id';
COMMENT ON COLUMN organization_remarks.updated_at IS 'updated_at';
COMMENT ON COLUMN organization_remarks.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN organization_remarks.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE organization_contacts IS 'organization_contacts';
COMMENT ON COLUMN organization_contacts.org_ctc_id IS 'org_ctc_id';
COMMENT ON COLUMN organization_contacts.org_id IS 'org_id';
COMMENT ON COLUMN organization_contacts.ctc_name IS 'ctc_name';
COMMENT ON COLUMN organization_contacts.is_primary IS 'is_primary';
COMMENT ON COLUMN organization_contacts.is_form_shipping IS 'is_form_shipping';
COMMENT ON COLUMN organization_contacts.is_result_shipping IS 'is_result_shipping';
COMMENT ON COLUMN organization_contacts.is_billing IS 'is_billing';
COMMENT ON COLUMN organization_contacts.zip_code IS 'zip_code';
COMMENT ON COLUMN organization_contacts.ard1 IS 'ard1';
COMMENT ON COLUMN organization_contacts.ard2 IS 'ard2';
COMMENT ON COLUMN organization_contacts.ard3 IS 'ard3';
COMMENT ON COLUMN organization_contacts.recipient_name IS 'recipient_name';
COMMENT ON COLUMN organization_contacts.honorific IS 'honorific';
COMMENT ON COLUMN organization_contacts.tel IS 'tel';
COMMENT ON COLUMN organization_contacts.tel2 IS 'tel2';
COMMENT ON COLUMN organization_contacts.fax IS 'fax';
COMMENT ON COLUMN organization_contacts.email IS 'email';
COMMENT ON COLUMN organization_contacts.memo IS 'memo';
COMMENT ON COLUMN organization_contacts.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN organization_contacts.created_at IS 'created_at';
COMMENT ON COLUMN organization_contacts.created_user_id IS 'created_user_id';
COMMENT ON COLUMN organization_contacts.created_session_id IS 'created_session_id';
COMMENT ON COLUMN organization_contacts.updated_at IS 'updated_at';
COMMENT ON COLUMN organization_contacts.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN organization_contacts.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE insurance_providers IS 'insurance_providers';
COMMENT ON COLUMN insurance_providers.insur_prov_id IS 'insur_prov_id';
COMMENT ON COLUMN insurance_providers.insur_prov_type_code IS 'insur_prov_type_code:0=None, 1=協会けんぽ, 2=代行機関, 3=健康保険組合, 4=国保, 5=その他';
COMMENT ON COLUMN insurance_providers.insur_prov_number IS 'insur_prov_number';
COMMENT ON COLUMN insurance_providers.insur_prov_name IS 'insur_prov_name';
COMMENT ON COLUMN insurance_providers.memo IS 'memo';
COMMENT ON COLUMN insurance_providers.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN insurance_providers.created_at IS 'created_at';
COMMENT ON COLUMN insurance_providers.created_user_id IS 'created_user_id';
COMMENT ON COLUMN insurance_providers.created_session_id IS 'created_session_id';
COMMENT ON COLUMN insurance_providers.updated_at IS 'updated_at';
COMMENT ON COLUMN insurance_providers.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN insurance_providers.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE policies IS 'policies';
COMMENT ON COLUMN policies.policy_code IS 'policy_code';
COMMENT ON COLUMN policies.policy_name IS 'policy_name';
COMMENT ON COLUMN policies.data_type IS 'data_type';
COMMENT ON COLUMN policies.policy_value IS 'policy_value';
COMMENT ON COLUMN policies.policy_desc IS 'policy_desc';
COMMENT ON COLUMN policies.is_active IS 'is_active';
COMMENT ON COLUMN policies.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN policies.created_at IS 'created_at';
COMMENT ON COLUMN policies.created_user_id IS 'created_user_id';
COMMENT ON COLUMN policies.created_session_id IS 'created_session_id';
COMMENT ON COLUMN policies.updated_at IS 'updated_at';
COMMENT ON COLUMN policies.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN policies.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE user_roles IS 'user_roles';
COMMENT ON COLUMN user_roles.user_id IS 'user_id';
COMMENT ON COLUMN user_roles.role_id IS 'role_id';
COMMENT ON COLUMN user_roles.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN user_roles.created_at IS 'created_at';
COMMENT ON COLUMN user_roles.created_user_id IS 'created_user_id';
COMMENT ON COLUMN user_roles.created_session_id IS 'created_session_id';
COMMENT ON COLUMN user_roles.updated_at IS 'updated_at';
COMMENT ON COLUMN user_roles.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN user_roles.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE roles IS 'roles';
COMMENT ON COLUMN roles.role_id IS 'role_id';
COMMENT ON COLUMN roles.role_name IS 'role_name';
COMMENT ON COLUMN roles.role_desc IS 'role_desc';
COMMENT ON COLUMN roles.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN roles.created_at IS 'created_at';
COMMENT ON COLUMN roles.created_user_id IS 'created_user_id';
COMMENT ON COLUMN roles.created_session_id IS 'created_session_id';
COMMENT ON COLUMN roles.updated_at IS 'updated_at';
COMMENT ON COLUMN roles.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN roles.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE role_permissions IS 'role_permissions';
COMMENT ON COLUMN role_permissions.role_id IS 'role_id';
COMMENT ON COLUMN role_permissions.perm_id IS 'perm_id';
COMMENT ON COLUMN role_permissions.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN role_permissions.created_at IS 'created_at';
COMMENT ON COLUMN role_permissions.created_user_id IS 'created_user_id';
COMMENT ON COLUMN role_permissions.created_session_id IS 'created_session_id';
COMMENT ON COLUMN role_permissions.updated_at IS 'updated_at';
COMMENT ON COLUMN role_permissions.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN role_permissions.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE permissions IS 'permissions';
COMMENT ON COLUMN permissions.perm_id IS 'perm_id';
COMMENT ON COLUMN permissions.perm_name IS 'perm_name';
COMMENT ON COLUMN permissions.perm_desc IS 'perm_desc';
COMMENT ON COLUMN permissions.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN permissions.created_at IS 'created_at';
COMMENT ON COLUMN permissions.created_user_id IS 'created_user_id';
COMMENT ON COLUMN permissions.created_session_id IS 'created_session_id';
COMMENT ON COLUMN permissions.updated_at IS 'updated_at';
COMMENT ON COLUMN permissions.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN permissions.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE users IS 'users';
COMMENT ON COLUMN users.user_id IS 'user_id';
COMMENT ON COLUMN users.login_name IS 'login_name';
COMMENT ON COLUMN users.email IS 'email';
COMMENT ON COLUMN users.display_name IS 'display_name';
COMMENT ON COLUMN users.password_hash IS 'password_hash';
COMMENT ON COLUMN users.password_salt IS 'password_salt';
COMMENT ON COLUMN users.expire_date IS 'expire_date';
COMMENT ON COLUMN users.failed_attempt_count IS 'failed_attempt_count:ログイン成功でリセットします';
COMMENT ON COLUMN users.locked_until_at IS 'locked_until_at:ロックされたら更新します';
COMMENT ON COLUMN users.last_login_at IS 'last_login_at';
COMMENT ON COLUMN users.last_logout_at IS 'last_logout_at:login_atより前を探すため初期値は同じとします。';
COMMENT ON COLUMN users.user_info IS 'user_info';
COMMENT ON COLUMN users.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN users.created_at IS 'created_at';
COMMENT ON COLUMN users.created_user_id IS 'created_user_id';
COMMENT ON COLUMN users.created_session_id IS 'created_session_id';
COMMENT ON COLUMN users.updated_at IS 'updated_at';
COMMENT ON COLUMN users.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN users.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE patients IS 'patients';
COMMENT ON COLUMN patients.pt_id IS 'pt_id';
COMMENT ON COLUMN patients.karte_number IS 'karte_number';
COMMENT ON COLUMN patients.pt_full_name IS 'pt_full_name';
COMMENT ON COLUMN patients.pt_full_name_katakana IS 'pt_full_name_katakana';
COMMENT ON COLUMN patients.pt_full_name_katakana_normalized IS 'pt_full_name_katakana_normalized:トリガで更新、全角化、区切り文字の統一、unaccent';
COMMENT ON COLUMN patients.pt_given_name IS 'pt_given_name';
COMMENT ON COLUMN patients.pt_old_full_name IS 'pt_old_full_name';
COMMENT ON COLUMN patients.birth_date IS 'birth_date';
COMMENT ON COLUMN patients.sex_code IS 'sex_code:0: None, 1: Man, 2: Woman, 9: Unknown';
COMMENT ON COLUMN patients.memo IS 'memo';
COMMENT ON COLUMN patients.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN patients.created_at IS 'created_at';
COMMENT ON COLUMN patients.created_user_id IS 'created_user_id';
COMMENT ON COLUMN patients.created_session_id IS 'created_session_id';
COMMENT ON COLUMN patients.updated_at IS 'updated_at';
COMMENT ON COLUMN patients.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN patients.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE organizations IS 'organizations';
COMMENT ON COLUMN organizations.org_id IS 'org_id';
COMMENT ON COLUMN organizations.insur_prov_type_code IS 'insur_prov_type_code';
COMMENT ON COLUMN organizations.insur_prov_id IS 'insur_prov_id';
COMMENT ON COLUMN organizations.parent_org_id IS 'parent_org_id';
COMMENT ON COLUMN organizations.org_number IS 'org_number:病院採番や法人番号';
COMMENT ON COLUMN organizations.org_name IS 'org_name';
COMMENT ON COLUMN organizations.org_name_katakana IS 'org_name_katakana';
COMMENT ON COLUMN organizations.org_name_katakana_normalized IS 'org_name_katakana_normalized';
COMMENT ON COLUMN organizations.org_name_display IS 'org_name_display';
COMMENT ON COLUMN organizations.org_name_print IS 'org_name_print';
COMMENT ON COLUMN organizations.memo IS 'memo';
COMMENT ON COLUMN organizations.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN organizations.created_at IS 'created_at';
COMMENT ON COLUMN organizations.created_user_id IS 'created_user_id';
COMMENT ON COLUMN organizations.created_session_id IS 'created_session_id';
COMMENT ON COLUMN organizations.updated_at IS 'updated_at';
COMMENT ON COLUMN organizations.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN organizations.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_daily_bookings IS 'reservation_daily_bookings';
COMMENT ON COLUMN reservation_daily_bookings.resv_daily_bkg_id IS 'resv_daily_bkg_id';
COMMENT ON COLUMN reservation_daily_bookings.bkg_date IS 'bkg_date:未定がある';
COMMENT ON COLUMN reservation_daily_bookings.floor_id IS 'floor_id';
COMMENT ON COLUMN reservation_daily_bookings.slot IS 'slot';
COMMENT ON COLUMN reservation_daily_bookings.ampm_code IS 'ampm_code:集計用 0: None, 1: AM, 2: PM';
COMMENT ON COLUMN reservation_daily_bookings.sex_code IS 'sex_code:集計用 0: None, 1: Man, 2: Woman, 9: Unknown';
COMMENT ON COLUMN reservation_daily_bookings.bkg_user_id IS 'bkg_user_id';
COMMENT ON COLUMN reservation_daily_bookings.bkg_at IS 'bkg_at';
COMMENT ON COLUMN reservation_daily_bookings.bkg_symbol_text IS 'bkg_symbol_text';
COMMENT ON COLUMN reservation_daily_bookings.bkg_remark_text IS 'bkg_remark_text';
COMMENT ON COLUMN reservation_daily_bookings.is_held IS 'is_held:仮押さえ';
COMMENT ON COLUMN reservation_daily_bookings.org_id IS 'org_id';
COMMENT ON COLUMN reservation_daily_bookings.resv_count IS 'resv_count:団体まとめ予約用';
COMMENT ON COLUMN reservation_daily_bookings.pt_id IS 'pt_id';
COMMENT ON COLUMN reservation_daily_bookings.order_id IS 'order_id';
COMMENT ON COLUMN reservation_daily_bookings.sub_order_id IS 'sub_order_id';
COMMENT ON COLUMN reservation_daily_bookings.is_cancelled IS 'is_cancelled';
COMMENT ON COLUMN reservation_daily_bookings.noshow_count IS 'noshow_count:すっぽかし回数';
COMMENT ON COLUMN reservation_daily_bookings.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_daily_bookings.created_at IS 'created_at';
COMMENT ON COLUMN reservation_daily_bookings.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_daily_bookings.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_daily_bookings.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_daily_bookings.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_daily_bookings.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_daily_slots IS 'reservation_daily_slots';
COMMENT ON COLUMN reservation_daily_slots.resv_daily_slot_id IS 'resv_daily_slot_id';
COMMENT ON COLUMN reservation_daily_slots.start_date IS 'start_date';
COMMENT ON COLUMN reservation_daily_slots.end_date IS 'end_date';
COMMENT ON COLUMN reservation_daily_slots.dow_code IS 'dow_code';
COMMENT ON COLUMN reservation_daily_slots.floor_id IS 'floor_id';
COMMENT ON COLUMN reservation_daily_slots.room_id IS 'room_id';
COMMENT ON COLUMN reservation_daily_slots.daily_cap IS 'daily_cap';
COMMENT ON COLUMN reservation_daily_slots.am_cap IS 'am_cap';
COMMENT ON COLUMN reservation_daily_slots.pm_cap IS 'pm_cap';
COMMENT ON COLUMN reservation_daily_slots.slots IS 'slots:''09:30, 09:30, 10:00, 10:00, EX''';
COMMENT ON COLUMN reservation_daily_slots.slot_caps IS 'slot_caps:''10, 10, 13, 13, 99''';
COMMENT ON COLUMN reservation_daily_slots.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_daily_slots.created_at IS 'created_at';
COMMENT ON COLUMN reservation_daily_slots.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_daily_slots.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_daily_slots.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_daily_slots.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_daily_slots.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_rooms IS 'reservation_rooms';
COMMENT ON COLUMN reservation_rooms.room_id IS 'room_id';
COMMENT ON COLUMN reservation_rooms.room_name IS 'room_name';
COMMENT ON COLUMN reservation_rooms.room_desc IS 'room_desc';
COMMENT ON COLUMN reservation_rooms.floor_id IS 'floor_id';
COMMENT ON COLUMN reservation_rooms.exam_cat_id IS 'exam_cat_id';
COMMENT ON COLUMN reservation_rooms.seq IS 'seq';
COMMENT ON COLUMN reservation_rooms.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_rooms.created_at IS 'created_at';
COMMENT ON COLUMN reservation_rooms.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_rooms.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_rooms.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_rooms.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_rooms.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_equipment_bookings IS 'reservation_equipment_bookings';
COMMENT ON COLUMN reservation_equipment_bookings.resv_equip_bkg_id IS 'resv_equip_bkg_id';
COMMENT ON COLUMN reservation_equipment_bookings.bkg_date IS 'bkg_date:未定がある';
COMMENT ON COLUMN reservation_equipment_bookings.equip_id IS 'equip_id';
COMMENT ON COLUMN reservation_equipment_bookings.slot IS 'slot';
COMMENT ON COLUMN reservation_equipment_bookings.bkg_user_id IS 'bkg_user_id';
COMMENT ON COLUMN reservation_equipment_bookings.bkg_at IS 'bkg_at';
COMMENT ON COLUMN reservation_equipment_bookings.bkg_symbol_text IS 'bkg_symbol_text';
COMMENT ON COLUMN reservation_equipment_bookings.bkg_remark_text IS 'bkg_remark_text';
COMMENT ON COLUMN reservation_equipment_bookings.is_held IS 'is_held:仮押さえ';
COMMENT ON COLUMN reservation_equipment_bookings.org_id IS 'org_id';
COMMENT ON COLUMN reservation_equipment_bookings.pt_id IS 'pt_id';
COMMENT ON COLUMN reservation_equipment_bookings.order_id IS 'order_id';
COMMENT ON COLUMN reservation_equipment_bookings.sub_order_id IS 'sub_order_id';
COMMENT ON COLUMN reservation_equipment_bookings.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_equipment_bookings.created_at IS 'created_at';
COMMENT ON COLUMN reservation_equipment_bookings.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_equipment_bookings.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_equipment_bookings.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_equipment_bookings.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_equipment_bookings.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_equipments IS 'reservation_equipments';
COMMENT ON COLUMN reservation_equipments.equip_id IS 'equip_id';
COMMENT ON COLUMN reservation_equipments.equip_name IS 'equip_name';
COMMENT ON COLUMN reservation_equipments.equip_desc IS 'equip_desc';
COMMENT ON COLUMN reservation_equipments.seq IS 'seq';
COMMENT ON COLUMN reservation_equipments.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_equipments.created_at IS 'created_at';
COMMENT ON COLUMN reservation_equipments.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_equipments.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_equipments.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_equipments.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_equipments.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_floors IS 'reservation_floors';
COMMENT ON COLUMN reservation_floors.floor_id IS 'floor_id';
COMMENT ON COLUMN reservation_floors.floor_name IS 'floor_name';
COMMENT ON COLUMN reservation_floors.floor_desc IS 'floor_desc';
COMMENT ON COLUMN reservation_floors.seq IS 'seq';
COMMENT ON COLUMN reservation_floors.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_floors.created_at IS 'created_at';
COMMENT ON COLUMN reservation_floors.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_floors.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_floors.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_floors.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_floors.updated_session_id IS 'updated_session_id';

COMMENT ON TABLE reservation_equipment_slots IS 'reservation_equipment_slots';
COMMENT ON COLUMN reservation_equipment_slots.resv_equip_slot_id IS 'resv_equip_slot_id';
COMMENT ON COLUMN reservation_equipment_slots.start_date IS 'start_date';
COMMENT ON COLUMN reservation_equipment_slots.end_date IS 'end_date:inclusive';
COMMENT ON COLUMN reservation_equipment_slots.dow_code IS 'dow_code:-1: None, 0: Sun, 1: Mon, ...';
COMMENT ON COLUMN reservation_equipment_slots.equip_id IS 'equip_id:0: None';
COMMENT ON COLUMN reservation_equipment_slots.slots IS 'slots:''09:30, 09:30, 10:00, 10:00, EX''';
COMMENT ON COLUMN reservation_equipment_slots.is_deleted IS 'is_deleted:ログ記録用';
COMMENT ON COLUMN reservation_equipment_slots.created_at IS 'created_at';
COMMENT ON COLUMN reservation_equipment_slots.created_user_id IS 'created_user_id';
COMMENT ON COLUMN reservation_equipment_slots.created_session_id IS 'created_session_id';
COMMENT ON COLUMN reservation_equipment_slots.updated_at IS 'updated_at';
COMMENT ON COLUMN reservation_equipment_slots.updated_user_id IS 'updated_user_id';
COMMENT ON COLUMN reservation_equipment_slots.updated_session_id IS 'updated_session_id';

