-- Project Name : authdb
-- Date/Time    : 2025/12/01 20:15:56
-- Author       : ted
-- RDBMS Type   : PostgreSQL
-- Application  : A5:SQL Mk-2

/*
  << 注意！！ >>
  BackupToTempTable, RestoreFromTempTable疑似命令が付加されています。
  これにより、drop table, create table 後もデータが残ります。
  この機能は一時的に $$TableName のような一時テーブルを作成します。
  この機能は A5:SQL Mk-2でのみ有効であることに注意してください。
*/

-- slow_operation_logs
-- * BackupToTempTable
DROP TABLE if exists "slow_operation_logs" CASCADE;

-- * RestoreFromTempTable
CREATE TABLE "slow_operation_logs" (
  "slow_operation_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
  , "operation_name" TEXT DEFAULT '' NOT NULL
  , "started_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
  , "finished_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
  , "duration_ms" BIGINT DEFAULT 0 NOT NULL
  , "user_id" UUID NOT NULL
  , "user_display_name" TEXT DEFAULT '' NOT NULL
  , "client_app_name" TEXT DEFAULT '' NOT NULL
  , "client_endpoint" TEXT DEFAULT '' NOT NULL
  , "additional_info" TEXT DEFAULT '' NOT NULL
) ;

CREATE UNIQUE INDEX "slow_operation_logs_PKI"
  ON "slow_operation_logs"("slow_operation_id");

ALTER TABLE "slow_operation_logs"
  ADD CONSTRAINT "slow_operation_logs_PKC" PRIMARY KEY ("slow_operation_id");

-- cache_updates
-- * BackupToTempTable
DROP TABLE if exists "cache_updates" CASCADE;

-- * RestoreFromTempTable
CREATE TABLE "cache_updates" (
  "table_name" TEXT DEFAULT '' NOT NULL
  , "latest_updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
  , "latest_updated_user_id" UUID NOT NULL
  , "latest_updated_session_id" UUID NOT NULL
) ;

CREATE UNIQUE INDEX "cache_updates_PKI"
  ON "cache_updates"("table_name");

ALTER TABLE "cache_updates"
  ADD CONSTRAINT "cache_updates_PKC" PRIMARY KEY ("table_name");

-- sessions
-- * BackupToTempTable
DROP TABLE if exists "sessions" CASCADE;

-- * RestoreFromTempTable
CREATE TABLE "sessions" (
  "session_id" UUID DEFAULT uuidv7() NOT NULL
  , "user_id" UUID NOT NULL
  , "user_display_name" TEXT DEFAULT '' NOT NULL
  , "client_app_name" TEXT DEFAULT '' NOT NULL
  , "client_endpoint" TEXT DEFAULT '' NOT NULL
  , "login_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
  , "logout_at" TIMESTAMPTZ
) ;

CREATE UNIQUE INDEX "sessions_PKI"
  ON "sessions"("session_id");

ALTER TABLE "sessions"
  ADD CONSTRAINT "sessions_PKC" PRIMARY KEY ("session_id");

-- change_logs
-- * BackupToTempTable
DROP TABLE if exists "change_logs" CASCADE;

-- * RestoreFromTempTable
CREATE TABLE "change_logs" (
  "change_log_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
  , "table_name" TEXT DEFAULT '' NOT NULL
  , "record_id" TEXT DEFAULT '' NOT NULL
  , "changed_action" TEXT DEFAULT '' NOT NULL
  , "changed_user_id" UUID NOT NULL
  , "changed_user_display_name" TEXT DEFAULT '' NOT NULL
  , "changed_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
  , "changed_session_id" UUID DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL
  , "sql_statement" TEXT DEFAULT '' NOT NULL
  , "old_values" JSONB DEFAULT '{}' NOT NULL
  , "new_values" JSONB DEFAULT '{}' NOT NULL
) ;

CREATE UNIQUE INDEX "change_logs_PKI"
  ON "change_logs"("change_log_id");

ALTER TABLE "change_logs"
  ADD CONSTRAINT "change_logs_PKC" PRIMARY KEY ("change_log_id");

COMMENT ON TABLE "slow_operation_logs" IS 'slow_operation_logs';
COMMENT ON COLUMN "slow_operation_logs"."slow_operation_id" IS 'slow_operation_id';
COMMENT ON COLUMN "slow_operation_logs"."operation_name" IS 'operation_name';
COMMENT ON COLUMN "slow_operation_logs"."started_at" IS 'started_at';
COMMENT ON COLUMN "slow_operation_logs"."finished_at" IS 'finished_at';
COMMENT ON COLUMN "slow_operation_logs"."duration_ms" IS 'duration_ms';
COMMENT ON COLUMN "slow_operation_logs"."user_id" IS 'user_id';
COMMENT ON COLUMN "slow_operation_logs"."user_display_name" IS 'user_display_name';
COMMENT ON COLUMN "slow_operation_logs"."client_app_name" IS 'client_app_name:バージョン含む';
COMMENT ON COLUMN "slow_operation_logs"."client_endpoint" IS 'client_endpoint:IPAddr, Port含む';
COMMENT ON COLUMN "slow_operation_logs"."additional_info" IS 'additional_info';

COMMENT ON TABLE "cache_updates" IS 'cache_updates';
COMMENT ON COLUMN "cache_updates"."table_name" IS 'table_name';
COMMENT ON COLUMN "cache_updates"."latest_updated_at" IS 'latest_updated_at';
COMMENT ON COLUMN "cache_updates"."latest_updated_user_id" IS 'latest_updated_user_id';
COMMENT ON COLUMN "cache_updates"."latest_updated_session_id" IS 'latest_updated_session_id';

COMMENT ON TABLE "sessions" IS 'sessions';
COMMENT ON COLUMN "sessions"."session_id" IS 'session_id';
COMMENT ON COLUMN "sessions"."user_id" IS 'user_id';
COMMENT ON COLUMN "sessions"."user_display_name" IS 'user_display_name';
COMMENT ON COLUMN "sessions"."client_app_name" IS 'client_app_name:バージョン含む';
COMMENT ON COLUMN "sessions"."client_endpoint" IS 'client_endpoint:IPAddr, Port含む';
COMMENT ON COLUMN "sessions"."login_at" IS 'login_at';
COMMENT ON COLUMN "sessions"."logout_at" IS 'logout_at';

COMMENT ON TABLE "change_logs" IS 'change_logs';
COMMENT ON COLUMN "change_logs"."change_log_id" IS 'change_log_id';
COMMENT ON COLUMN "change_logs"."table_name" IS 'table_name';
COMMENT ON COLUMN "change_logs"."record_id" IS 'record_id';
COMMENT ON COLUMN "change_logs"."changed_action" IS 'changed_action';
COMMENT ON COLUMN "change_logs"."changed_user_id" IS 'changed_user_id';
COMMENT ON COLUMN "change_logs"."changed_user_display_name" IS 'changed_user_display_name';
COMMENT ON COLUMN "change_logs"."changed_at" IS 'changed_at';
COMMENT ON COLUMN "change_logs"."changed_session_id" IS 'changed_session_id';
COMMENT ON COLUMN "change_logs"."sql_statement" IS 'sql_statement';
COMMENT ON COLUMN "change_logs"."old_values" IS 'old_values';
COMMENT ON COLUMN "change_logs"."new_values" IS 'new_values';

