<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FileBridge</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aloe.Apps.FileBridge.Dummy\Aloe.Apps.FileBridge.Dummy.csproj" />
    <ProjectReference Include="..\Aloe.Apps.FileBridgeLib\Aloe.Apps.FileBridgeLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Utils/Aloe.Utils.Hosting.Serilog/Aloe.Utils.Hosting.Serilog.csproj" />
  </ItemGroup>

</Project>
