<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <UserSecretsId>dotnet-AloeMedockResvServerMonitor-b0e3a93c-98b5-4860-a131-9f46d1809e9a</UserSecretsId>
    <RootNamespace>Aloe.Medock.Reservation.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <RollForward>LatestMinor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\MaterialIcons\add_16dp_75FB4C.png" />
    <None Remove="Assets\MaterialIcons\cancel_16dp_8C1AF6.png" />
    <None Remove="Assets\MaterialIcons\check_circle_16dp_75FB4C.ico" />
    <None Remove="Assets\MaterialIcons\check_circle_16dp_75FB4C.png" />
    <None Remove="Assets\MaterialIcons\circle_16dp_8C1AF6.png" />
    <None Remove="Assets\MaterialIcons\close_16dp_EA3323.ico" />
    <None Remove="Assets\MaterialIcons\close_16dp_EA3323.png" />
    <None Remove="Assets\MaterialIcons\do_not_disturb_16dp_EA3323.ico" />
    <None Remove="Assets\MaterialIcons\do_not_disturb_16dp_EA3323.png" />
    <None Remove="Assets\MaterialIcons\folder_open_16dp_F19E39.png" />
    <None Remove="Assets\MaterialIcons\hourglass_top_16dp_F19E39.ico" />
    <None Remove="Assets\MaterialIcons\hourglass_top_16dp_F19E39.png" />
    <None Remove="Assets\MaterialIcons\logout_16dp_8C1AF6.png" />
    <None Remove="Assets\MaterialIcons\pause_16dp_EA3323.ico" />
    <None Remove="Assets\MaterialIcons\pause_16dp_EA3323.png" />
    <None Remove="Assets\MaterialIcons\pause_circle_16dp_F19E39.png" />
    <None Remove="Assets\MaterialIcons\play_arrow_16dp_75FB4C.png" />
    <None Remove="Assets\MaterialIcons\play_circle_16dp_75FB4C.png" />
    <None Remove="Assets\MaterialIcons\remove_16dp_EA3323.png" />
    <None Remove="Assets\MaterialIcons\restart_alt_16dp_8C1AF6.png" />
    <None Remove="Assets\MaterialIcons\settings_16dp_75FBFD.png" />
    <None Remove="Assets\MaterialIcons\stop_16dp_EA3323.png" />
    <None Remove="Assets\MaterialIcons\stop_circle_16dp_EA3323.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\MaterialIcons\add_16dp_75FB4C.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\cancel_16dp_8C1AF6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\check_circle_16dp_75FB4C.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\circle_16dp_8C1AF6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\close_16dp_EA3323.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\do_not_disturb_16dp_EA3323.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\folder_open_16dp_F19E39.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\hourglass_top_16dp_F19E39.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\logout_16dp_8C1AF6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\pause_16dp_EA3323.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\pause_circle_16dp_F19E39.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\play_arrow_16dp_75FB4C.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\play_circle_16dp_75FB4C.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\remove_16dp_EA3323.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\restart_alt_16dp_8C1AF6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\settings_16dp_75FBFD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\stop_16dp_EA3323.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MaterialIcons\stop_circle_16dp_EA3323.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\AloeCoreLib.Logging\Aloe.Common.AloeCoreLib.Logging.csproj" />
    <ProjectReference Include="..\..\..\Common\AloeCoreLib.Win32\Aloe.Common.AloeCoreLib.Win32.csproj" />
    <ProjectReference Include="..\..\..\Common\AloeCoreLib\Aloe.Common.AloeCoreLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\MaterialIcons\done_16dp_75FB4C.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
