<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Data\**" />
    <None Remove="Models\**" />
    <Page Remove="Data\**" />
    <Page Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MagicOnion.Abstractions" Version="6.1.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreLib\AloeReservationGrid.Lib.CoreLib.csproj" />
  </ItemGroup>

</Project>
